name: Build Backports Tar (MediaTek mt76)

on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Mainline kernel repo'
        required: true
        default: 'https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git'
      source_branch:
        description: 'Kernel version tag'
        required: true
        default: 'v6.6'
      output_prefix:
        description: 'Output prefix'
        required: false
        default: 'backports-mt76'

jobs:
  build-backports:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: Checkout backports tool
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          apk update && apk add git python3 ocaml ocaml-compiler-libs ncurses-dev autoconf automake pkgconfig musl-dev make patch zstd

      - name: Build Coccinelle
        run: |
          git clone --depth=1 https://github.com/coccinelle/coccinelle.git
          cd coccinelle
          ./autogen && ./configure && make && make install

      - name: Clone source kernel
        env:
          REPO: ${{ github.event.inputs.source_repo }}
          BRANCH: ${{ github.event.inputs.source_branch }}
        run: git clone --depth=1 --branch ${BRANCH} ${REPO} source-kernel

      - name: Build Backports (MediaTek mt76)
        env:
          PREFIX: ${{ github.event.inputs.output_prefix }}
        run: |
          python3 gentree.py --clean --copy-list copy-list-mt76 source-kernel ${PREFIX}

      - name: Pack & Upload
        ...
